language: scala
scala:
  - 2.12.10
jdk:
  - openjdk8
  - openjdk11
  - openjdk13
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.cache/coursier
services:
  - docker
before_script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean flowLint test doc
branches:
  only:
    - master
before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
