import play.sbt.PlayScala._

name := "location"

ThisBuild / scalaVersion := "2.13.15"
ThisBuild / javacOptions ++= Seq("-source", "17", "-target", "17")

// Resolve scala-xml version dependency mismatch, see https://github.com/sbt/sbt/issues/7007
ThisBuild / libraryDependencySchemes ++= Seq(
  "org.scala-lang.modules" %% "scala-xml" % VersionScheme.Always,
  "org.scoverage" %% "sbt-scoverage" % VersionScheme.Always,
)

lazy val allScalacOptions = Seq(
  "-feature",
  "-Xfatal-warnings",
  "-unchecked",
  "-Xcheckinit",
  "-Xlint:adapted-args",
  "-Ypatmat-exhaust-depth",
  "100", // Fixes: Exhaustivity analysis reached max recursion depth, not all missing cases are reported.
  "-Wconf:src=generated/.*:silent",
  "-Wconf:src=target/.*:silent", // silence the unused imports errors generated by the Play Routes
)

lazy val generated = project
  .in(file("generated"))
  .enablePlugins(PlayScala)
  .settings(commonSettings: _*)
  .settings(
  )

lazy val api = project
  .in(file("api"))
  .dependsOn(generated)
  .enablePlugins(PlayScala)
  .enablePlugins(JavaAppPackaging, JavaAgent)
  .settings(commonSettings: _*)
  .settings(
    javaAgents += "com.datadoghq" % "dd-java-agent" % "1.43.0",
    Test / javaOptions += "-Dconfig.file=conf/application.test.conf",
    Test / javaOptions ++= Seq(
      "--add-exports=java.base/sun.security.x509=ALL-UNNAMED",
      "--add-opens=java.base/sun.security.ssl=ALL-UNNAMED",
    ),
    routesImport += "io.flow.location.v0.Bindables._",
    routesGenerator := InjectedRoutesGenerator,
    libraryDependencies ++= Seq(
      "io.flow" %% "lib-play-play28" % "0.8.8",
      "io.flow" %% "lib-metrics-play28" % "1.1.2",
      "io.flow" %% "lib-reference-scala" % "0.3.57",
      "io.flow" %% "lib-s3-play28" % "0.4.15",
      "com.google.maps" % "google-maps-services" % "2.0.0",
      "io.flow" %% "lib-healthcheck-play28" % "0.0.32",
      "org.scalacheck" %% "scalacheck" % "1.18.1" % "test",
      "io.flow" %% "lib-test-utils-play28" % "0.2.42" % Test,
      "io.flow" %% "lib-usage-play28" % "0.2.62",
      "io.flow" %% "lib-log" % "0.2.28",
    ),
  )

lazy val commonSettings: Seq[Setting[_]] = Seq(
  scalafmtOnCompile := true,
  name ~= ("location-" + _),
  libraryDependencies ++= Seq(
    "com.google.inject" % "guice" % "5.1.0",
    "com.google.inject.extensions" % "guice-assistedinject" % "5.1.0",
    "org.projectlombok" % "lombok" % "1.18.36" % "provided",
    ws,
    "com.typesafe.play" %% "play-json-joda" % "2.9.4",
    "com.typesafe.play" %% "play-json" % "2.9.4",
  ),
  Test / javaOptions ++= Seq(
    "--add-exports=java.base/sun.security.x509=ALL-UNNAMED",
    "--add-opens=java.base/sun.security.ssl=ALL-UNNAMED",
  ),
  scalacOptions ++= allScalacOptions,
  resolvers += "scalaz-bintray" at "https://dl.bintray.com/scalaz/releases",
  resolvers += "Artifactory" at "https://flow.jfrog.io/flow/libs-release/",
  coverageExcludedFiles := ".*\\/*generated*\\/.*",
  coverageDataDir := file("target/scala-2.13"),
  coverageHighlighting := true,
  coverageFailOnMinimum := true,
  coverageMinimumStmtTotal := 74,
  coverageMinimumBranchTotal := 64,
  credentials += Credentials(
    "Artifactory Realm",
    "flow.jfrog.io",
    System.getenv("ARTIFACTORY_USERNAME"),
    System.getenv("ARTIFACTORY_PASSWORD"),
  ),
)
version := "0.9.8"
