import play.sbt.PlayScala._

name := "location"

ThisBuild / scalaVersion := "2.13.6"

lazy val allScalacOptions = Seq(
  "-feature",
  "-Xfatal-warnings",
  "-unchecked",
  "-Xcheckinit",
  "-Xlint:adapted-args",
  "-Ypatmat-exhaust-depth", "100", // Fixes: Exhaustivity analysis reached max recursion depth, not all missing cases are reported.
  "-Wconf:src=generated/.*:silent",
  "-Wconf:src=target/.*:silent", // silence the unused imports errors generated by the Play Routes
)

lazy val generated = project
  .in(file("generated"))
  .enablePlugins(PlayScala)
  .settings(commonSettings: _*)
  .settings(
  )

lazy val api = project
  .in(file("api"))
  .dependsOn(generated)
  .enablePlugins(PlayScala)
  .enablePlugins(NewRelic)
  .enablePlugins(JavaAppPackaging, JavaAgent)
  .settings(commonSettings: _*)
  .settings(
    javaAgents += "com.datadoghq" % "dd-java-agent" % "0.115.0",
    Test / javaOptions += "-Dconfig.file=conf/application.test.conf",
    routesImport += "io.flow.location.v0.Bindables._",
    routesGenerator := InjectedRoutesGenerator,
    libraryDependencies ++= Seq(
      "io.flow" %% "lib-play-play28" % "0.7.44",
      "io.flow" %% "lib-metrics-play28" % "1.0.38",
      "io.flow" %% "lib-reference-scala" % "0.3.9",
      "io.flow" %% "lib-s3-play28" % "0.3.59",
      "com.google.maps" % "google-maps-services" % "2.0.0",
      "org.scalacheck" %% "scalacheck" % "1.17.0" % "test",
      "io.flow" %% "lib-test-utils-play28" % "0.1.81" % Test,
      "io.flow" %% "lib-usage-play28" % "0.1.99",
      "io.flow" %% "lib-log" % "0.1.77"
    ),
  )

lazy val commonSettings: Seq[Setting[_]] = Seq(
  name ~= ("location-" + _),
  libraryDependencies ++= Seq(
    guice,
    ws,
    "com.typesafe.play" %% "play-json-joda" % "2.9.3",
    "com.typesafe.play" %% "play-json" % "2.9.3",
  ),
  scalacOptions ++= allScalacOptions,
  resolvers += "scalaz-bintray" at "https://dl.bintray.com/scalaz/releases",
  resolvers += "Artifactory" at "https://flow.jfrog.io/flow/libs-release/",
  credentials += Credentials(
    "Artifactory Realm",
    "flow.jfrog.io",
    System.getenv("ARTIFACTORY_USERNAME"),
    System.getenv("ARTIFACTORY_PASSWORD")
  )
)
version := "0.8.12"
