import play.sbt.PlayScala._

name := "location"

scalaVersion in ThisBuild := "2.12.10"

lazy val generated = project
  .in(file("generated"))
  .enablePlugins(PlayScala)
  .settings(commonSettings: _*)
  .settings(
    flowGeneratedFiles ++= Seq(
      ".*".r,
    ),
  )

lazy val api = project
  .in(file("api"))
  .dependsOn(generated)
  .enablePlugins(PlayScala)
  .enablePlugins(NewRelic)
  .enablePlugins(JavaAppPackaging, JavaAgent)
  .settings(commonSettings: _*)
  .settings(
    javaAgents += "io.kamon" % "kanela-agent" % "1.0.4",
    javaOptions in Test += "-Dconfig.file=conf/application.test.conf",
    routesImport += "io.flow.location.v0.Bindables._",
    routesGenerator := InjectedRoutesGenerator,
    libraryDependencies ++= Seq(
      "io.flow" %% "lib-play-play26" % "0.5.89",
      "io.flow" %% "lib-play-graphite-play26" % "0.1.30",
      "io.flow" %% "lib-reference-scala" % "0.2.34",
      "io.flow" %% "lib-s3-play26" % "0.2.79",
      "com.google.maps" % "google-maps-services" % "0.10.2",
      "org.scalacheck" %% "scalacheck" % "1.14.3" % "test",
      "io.flow" %% "lib-test-utils" % "0.0.78" % Test,
      "io.flow" %% "lib-usage" % "0.1.13",
      "io.flow" %% "lib-log" % "0.0.97"
    ),
    // silence all warnings on autogenerated files
    flowGeneratedFiles ++= Seq(
      "target/.*".r,
    ),
    // Make sure you only exclude warnings for the project directories, i.e. make builds reproducible
    scalacOptions += s"-P:silencer:sourceRoots=${baseDirectory.value.getCanonicalPath}"
  )

lazy val commonSettings: Seq[Setting[_]] = Seq(
  name ~= ("location-" + _),
  libraryDependencies ++= Seq(
    guice,
    ws,
    "com.typesafe.play" %% "play-json-joda" % "2.7.4",
    "com.typesafe.play" %% "play-json" % "2.8.1",
    compilerPlugin("com.github.ghik" %% "silencer-plugin" % "1.4.2"),
    "com.github.ghik" %% "silencer-lib" % "1.4.2" % Provided
  ),
  resolvers += "scalaz-bintray" at "https://dl.bintray.com/scalaz/releases",
  resolvers += "Artifactory" at "https://flow.jfrog.io/flow/libs-release/",
  credentials += Credentials(
    "Artifactory Realm",
    "flow.jfrog.io",
    System.getenv("ARTIFACTORY_USERNAME"),
    System.getenv("ARTIFACTORY_PASSWORD")
  )
)
version := "0.6.6"
