nameOverride: "location"
fullnameOverride: "location"

service:
  startupHealthcheckEndpoint: /_internal_/startup
  livenessHealthcheckEndpoint: /_internal_/live
  readinessHealthcheckEndpoint: /_internal_/ready
  
team: "core"

image:
  repository: flowcommerce/location

resources:
  limits:
    memory: "7100Mi"
    cpu: 2
  requests:
    memory: "7100Mi"
    cpu: 500m

jvmOpts:
    memory: 6100m

nodeSelector:
  karpenter/role: workers
tolerations:
  - key: "role"
    operator: "Equal"
    value: "workers"
    effect: "NoSchedule"
topologySpreadConstraints:
  schedule: "DoNotSchedule"

deployments:
  live:
    minReplicas: 3
    maxReplicas: 3
    maxUnavailable: 1
    serviceAccountName: "flow-prod-eks-production-location-sa"
    serviceAccountIamRole: "arn:aws:iam::479720515435:role/flow-prod-eks-production-role"

rollout:
  enabled: true
  defaultAnalysis:
    errorRate:
      successCondition: default(result, 0) <= 0.0
    p50ResponseTime:
      successCondition: default(result, 0) < 0.005
      failureLimit: 1
    p95ResponseTime:
      successCondition: default(result, 0) < 0.1

datadogMonitors:
- type: trace.akka_http.request.errors-sum
- type: trace.akka_http.request-avg
