nameOverride: "location"
fullnameOverride: "location"

service:
  startupHealthcheckEndpoint: /_internal_/startup
  livenessHealthcheckEndpoint: /_internal_/live
  readinessHealthcheckEndpoint: /_internal_/ready
  
team: "core"

iamRole: arn:aws:iam::479720515435:role/ecsInstanceRole
image:
  repository: flowcommerce/location

resources:
  limits:
    memory: "7500Mi"
  requests:
    memory: "7500Mi"
    cpu: 1

jvmOpts:
    memory: 6300m

deployments:
  live:
    minReplicas: 4
    maxReplicas: 4
    maxUnavailable: 1

rollout:
  enabled: true
  defaultAnalysis:
    errorRate:
      successCondition: default(result, 0) <= 0.0
    p50ResponseTime:
      successCondition: default(result, 0) < 0.005
      failureLimit: 1
    p95ResponseTime:
      successCondition: default(result, 0) < 0.1

datadogMonitors:
- type: trace.akka_http.request.errors-sum
- type: trace.akka_http.request-avg
