nameOverride: "location"
fullnameOverride: "location"

team: "core"

iamRole: arn:aws:iam::479720515435:role/ecsInstanceRole
image:
  repository: flowcommerce/location

resources:
  limits:
    memory: "7100Mi"
  requests:
    memory: "7100Mi"
    cpu: 1

jvmOpts:
    memory: 6100m

deployments:
  live:
    minReplicas: 3
    maxReplicas: 3
    maxUnavailable: 1

rollout:
  enabled: true
  analysis:
    - name: error-rate
      successCondition: default(result, 0) <= 0.0
      provider:
        datadog:
          query: |
            sum:trace.akka_http.request.errors{service:location}.as_count()  /
            sum:trace.akka_http.request.hits{service:location}.as_count()
    - name: response-time-p50
      successCondition: default(result, 0) < 0.002
      provider:
        datadog:
          query: p50:trace.akka_http.request{service:location}
    - name: response-time-p95
      successCondition: default(result, 0) < 0.1
      provider:
        datadog:
          query: p95:trace.akka_http.request{service:location}
