nameOverride: "location"
fullnameOverride: "location"

team: "core"

iamRole: arn:aws:iam::479720515435:role/ecsInstanceRole
image:
  repository: flowcommerce/location

resources:
  limits:
    memory: "7100Mi"
    cpu: 1
  requests:
    memory: "7100Mi"
    cpu: 1

jvmOpts:
    memory: 6100m

deployments:
  live:
    minReplicas: 3
    maxReplicas: 3
    maxUnavailable: 1

rolloutResource:
    enabled: false

canary: 
    # Disable this to follow the default RollingUpdate Strategy
<<<<<<< HEAD
    enabled: false
    
=======
    enabled: false
>>>>>>> eacd895b88e8a21bca45826b2ea31af405848f43
